# Generated by Django 4.1.3 on 2022-11-23 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.PositiveBigIntegerField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('completedOrder', models.BooleanField(default=False)),
                ('productAdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.product')),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualEnd', models.DateTimeField(default=django.utils.timezone.now)),
                ('delayTime', models.DurationField(default=datetime.timedelta(0))),
                ('startedJob', models.BooleanField(blank=True, default=False, null=True)),
                ('completedJob', models.BooleanField(blank=True, default=False, null=True)),
                ('rank', models.PositiveBigIntegerField()),
                ('machine', models.ManyToManyField(blank=True, to='input.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleView.order')),
                ('proccess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='input.proccess')),
                ('worker', models.ManyToManyField(blank=True, to='input.worker')),
            ],
        ),
    ]
