# Generated by Django 4.1.3 on 2022-12-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleView', '0003_job_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='data',
            new_name='machData',
        ),
        migrations.AddField(
            model_name='job',
            name='quantData',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
