# Generated by Django 4.1.3 on 2022-12-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleView', '0004_rename_data_job_machdata_job_quantdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='quantData',
            new_name='workData',
        ),
    ]
